### ISSUE TITLE
Proposal: Incent the liquidity providers to balance their portfolio in Round XIA

### ISSUE THREAD

**Issue by jie85** [mcdexio/liquidity-mining#25]
## Motivation
Since the liquidity mining starts on July 8th, more than 80 liquidity providers (LP) deposited a total of 4,500 ETH into the AMM, which is definitely a good start of liquidity mining. 

However, the team provided a default liquidity mining strategy called "50/50 strategy", which has risk exposure of 50%ETH+50%USD. This strategy is comfortable because it reduces the beta of the LP's investment. To obtain the 50%USD exposure, the liquidity provider needs to short ETH-PERP in MCDEX. As a result, there are too many shorts, incented by the mining rewards, in the market, leading to significant pressure on the price and an extremely high funding rate(about APY 400%).

Liquidity providers are fatal roles in this market. They should be the balancer of the Ecos-system. The LP has a portfolio made up of the position in his margin account and parts of the  AMM's position (short position in ETH-PERP's AMM).  LP should be neural. Thus the net position size of LP's portfolio should be zero.

If the LP has no position at the beginning, after adding liquidity, he will get a long position in his margin account and a short position in the AMM. The long position size is equal to the short position size, making the portfolio's net position size be zero. Therefore, the LP has an exposure of 100%ETH. However, as the traders trade against the AMM, the position size of the AMM changes, resulting in the net position of LP's portfolio not equal to zero anymore. In this case, the LP should change their position size in their margin account correspondingly and make the net position return to zero, which we called "rebalance the portfolio."

I propose to change the liquidity mining rule of XIA to incent the miners to not only provide liquidity but also rebalance their portfolio.

## Mining Reward Distribution Rules

1. The mining rewards are calculated in every block.

2. The LP_i's position in AMM:

```
Position_In_AMM_i = Share_Token_Balance_i / Total_Share_Token_Supply * Total_Position_In_AMM
```

3. The net position of LP_j' portfolio:

```
Portfolio_Position_i = Position_in_AMM_i + Positon_In_Margin_Account_i
```

4. The imbalance rate of LP_j's portfolio:

```
Imbalance_Rate_i = ABS(Portfolio_Position_i) / ABS(Position_in_AMM_i)
```

5. The mining effective share of LP_i:
```
Effective_Share_i = Share_Token_Balance_i    If Imbalance_Rate_i <= 10%
Effective_Share_i = Share_Token_Balance_i * (89/80 - Imbalance_Rate_i * 9/8)  if  10% <  Imbalance_Rate_i < 90%
Effective_Share_i = Share_Token_Balance_i * 0.1    If Imbalance_Rate_i >= 90%
```
It means that if the LP's imbalance rate is below 10%, he can still get the same mining reward with that of a fully balanced portfolio.

```
Invalid_Mining_Share_i = Share_Token_Balance_i  - Effective_Share_i 
```

6. The mining rewards of LP_i of AMM_j:

```
Reward_LP_j = Effective_Share_i / SUM(Effective_Share_k) * Reward_AMM_j
```

7. The AMM_j's total effective mining value:
```
Effective_Value_j = SUM(Effective_Share_k) / Total_Share_Token_Supply * Margin_Balance_In_USD_j
```

8. Distribute the mining rewards (2MCB/block) among the AMMs:
```
Reward_AMM_j = Effective_Value_j / SUM(Effective_Value_k) * 2MCB
```

## Execution Plan

I suggest using the rules above since 25% progress of round XIA (block height 10,471,250, about July 16).  

And we should provide good UI to show the liquidity provider's portfolio's status, including net position, imbalance rate, effective mining shares, and so on. Besides, we should provide a good UI/guide to help liquidity provider to rebalance their portfolio.

We request the community to comment on this proposal.

**Comment by sulliwane** [comment]
Positive:
- this proposal will force LPs to better understand how the platform works.
- this proposal will force the community to better reflect on the role of the LPs (ex: are LPs expected to just provide liquidity, and "forget" about it. Or are they expected to keep neutral exposure and be more "proactive/sophisticated" with "bots" and so on?)
- side effect: this proposal will naturally grow a bit the volume on the platform (to be confirmed?)

Questions:
- how much GAS & trading fees it costs to LPs to rebalance their position (ex: when imbalance crosses over 10%)?
- How will LPs be notified about the imbalance? (Apart from manually checking every hours/days/weeks).
- Beyond solving this short term issue, could the team expand a bit more on the kind of problems it could create in the longer run (how "sustainable" is this solution? Just trying to anticipate a bit on the questions it will raise)

**Comment by Quixote19** [comment]
Please spend time making the UI as clear as possible, I believe this is important.

**Comment by jie85** [comment]
> Positive:
> 
> * this proposal will force LPs to better understand how the platform works.
> * this proposal will force the community to better reflect on the role of the LPs (ex: are LPs expected to just provide liquidity, and "forget" about it. Or are they expected to keep neutral exposure and be more "proactive/sophisticated" with "bots" and so on?)
> * side effect: this proposal will naturally grow a bit the volume on the platform (to be confirmed?)
> 
> Questions:
> 
> * how much GAS & trading fees it costs to LPs to rebalance their position (ex: when imbalance crosses over 10%)?
> * How will LPs be notified about the imbalance? (Apart from manually checking every hours/days/weeks).
> * Beyond solving this short term issue, could the team expand a bit more on the kind of problems it could create in the longer run (how "sustainable" is this solution? Just trying to anticipate a bit on the questions it will raise)


"side effect: this proposal will naturally grow a bit the volume on the platform"  -- I think so, but should be very little, because of the 10% threshold.

1. in most cases, the LPs need only to trade to rebalance. The rebalance UI will use the order book to do such trade. So the fee is equal to trade on the order book. 
2. it is a good question. If the ETH price does not change and the traders' demand is balanced(the same number of long & short) the 10% threshold makes the LPs do not need to rebalance. If the traders' demand is balanced but ETH price changes, the 10% threshold makes the LPs only need to rebalance when the price change rate is over 20%. What's more, even the LPs have an imbalance rate, they could still get mining rewards.  So, I think the LPs need to rebalance about once several days. In the beginning, the LPs need to check the imbalance rate in the UI. However, we may add an email notification feature to notify the imbalance rate or something like that.
3. I think the AMM's design is totally independent of liquidity mining. So, even if there is no liquidity mining at all, the LPs can still use some strategy to invest in AMM as liquidity providers. For example, the 50/50 stragetry provides a comfortable investment strategy, which reduces the Beta and gains the trading fee, even without the mining reward.  With liquidity mining, LPs should take the incentive as a kind of investment reward. So the LPs should trade-off between the rewards(mining rewards + AMM trading fee rewards) and the cost (risk exposures, rebalance fees).  I suggest the LPs to design their own strategies according to their risk appetite. Besides, the community could develop more strategies.

**Comment by jie85** [comment]
1. The pool from Telegram group
Yes: 18 votes
No: 7 votes
Yes ASAP: 3 votes
![image](https://user-images.githubusercontent.com/7948466/87273365-7b2bc680-c50b-11ea-9a0f-406a0e0da4c3.png)

2. The pool from Wechat group
Yes: 17
No: 9
Yes ASAP: 1
![image](https://user-images.githubusercontent.com/7948466/87273914-f346bc00-c50c-11ea-99ea-6d4d0c692768.png)

**Comment by jean1101** [comment]
**Announcement**
As per the feedback from the community, the new liquidity mining proposal will be effective from block height 10,471,250 (July 16).

From then on, the 50/50 strategy will only enjoy 10% of the original share token. We strongly suggest LP to rebalance to maintain the balance of the ecosystem.
